name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - uses: Swatinem/rust-cache@v2

      - uses: prefix-dev/setup-pixi@v0.8.1
        with:
          activate-environment: true
          cache: true
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}
          manifest-path: build/pixi.toml

      - name: Tweak environment to find GDAL
        run: |
          echo "PKG_CONFIG_PATH=$(pwd)/build/.pixi/envs/default/lib/pkgconfig" >> "$GITHUB_ENV"
          echo "LD_LIBRARY_PATH=$(pwd)/build/.pixi/envs/default/lib" >> "$GITHUB_ENV"

      - name: Fmt
        run: cargo fmt -- --check

      - name: Clippy
        run: cargo clippy -- -D warnings

      - name: Test
        run: cargo test
