name: Publish to crates.io

on:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish to crates.io
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - uses: Swatinem/rust-cache@v2

      - name: Extract current version
        id: version
        run: |
          version=$(cargo metadata --no-deps --format-version 1 | jq -r '.packages[0].version')
          echo "version=$version" >> "$GITHUB_OUTPUT"

      - name: Verify version bump
        run: |
          crate_name=$(cargo metadata --no-deps --format-version 1 | jq -r '.packages[0].name')
          published_version=$(curl -s "https://crates.io/api/v1/crates/$crate_name" | jq -r '.crate.max_version')
          echo "Published version on crates.io: $published_version"
          echo "Local version in Cargo.toml: $version"
          if [ "$published_version" = "$version" ]; then
            echo "Error: Version $version is already published. Please bump the version in Cargo.toml before publishing."
            exit 1
          fi

      - uses: prefix-dev/setup-pixi@v0.8.1
        with:
          activate-environment: true
          cache: true
          cache-write: false
          manifest-path: build/pixi.toml

      - name: Tweak environment to find GDAL
        run: |
          echo "PKG_CONFIG_PATH=$(pwd)/build/.pixi/envs/default/lib/pkgconfig" >> "$GITHUB_ENV"
          echo "LD_LIBRARY_PATH=$(pwd)/build/.pixi/envs/default/lib" >> "$GITHUB_ENV"

      - name: Fmt
        run: cargo fmt -- --check

      - name: Clippy
        run: cargo clippy -- -D warnings

      - name: Test
        run: cargo test

      - name: Publish to crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish --token $CARGO_REGISTRY_TOKEN
